services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logsAnalyzeDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres -d logsAnalyzeDb"
      interval: 2s
      timeout: 20s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: smartloganalyzer-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logsAnalyzeDb?currentSchema=log_common
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: smartloganalyzer-frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped

  fluentBit:
    image: cr.fluentbit.io/fluent/fluent-bit:3.0
    container_name: fluentbit
    ports:
      - "2020:2020"
    volumes:
      - ./fluentbit-configs/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logs-datasets:/logs-datasets:ro
      - ./fluentbit-configs/parsers.conf:/parsers:ro
      - ./fluentbit-configs/enrich.lua:/fluent-bit/etc/enrich.lua:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: