[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /parsers

[INPUT]
    Name         tail
    Tag          hadoop
    Path         /logs-datasets/hadoop/*.log
    Parser       hadoop_log
    Read_from_Head True
    Refresh_Interval 5

[INPUT]
    Name         tail
    Tag          linux
    Path         /logs-datasets/linux/*.log
    Parser       linux_syslog
    Read_from_Head True
    Refresh_Interval 5

[FILTER]
    Name    lua
    Match   linux
    script  /fluent-bit/etc/enrich.lua
    call    enrich_linux_log

[FILTER]
    Name    lua
    Match   *
    script  /fluent-bit/etc/enrich.lua
    call    add_service_name

[OUTPUT]
    Name         http
    Match        *
    Host         host.docker.internal
    Port         8080
    URI          /api/logs
    Format       json
    Json_date_key timestamp
    Json_date_format iso8601

[OUTPUT]
    Name         stdout
    Match        *
    Format       json_lines